name: check

on: [push]

jobs:
  check:
    runs-on: [windows-latest]

    steps:
      - name: git config
        run: git config --list
    
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
    
      - name: type info
        shell: cmd
        run: type submodule_actions\README.md
